"""Final fix for user model

Revision ID: 513d1f639f3e
Revises: 
Create Date: 2026-02-01 18:23:21.144918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '513d1f639f3e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('orders', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('orders', sa.Column('final_price', sa.Float(), nullable=False))
    op.add_column('orders', sa.Column('status', sa.Enum('EN_ATTENTE', 'EN_PREPARATION', 'TERMINE', 'ANNULE', name='orderstatus'), nullable=True))
    op.drop_column('orders', 'total_price')
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.drop_index(op.f('email'), table_name='users')
    op.drop_index(op.f('username'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('username'), 'users', ['username'], unique=True)
    op.create_index(op.f('email'), 'users', ['email'], unique=True)
    op.drop_column('users', 'is_active')
    op.add_column('orders', sa.Column('total_price', mysql.FLOAT(), nullable=True))
    op.drop_column('orders', 'status')
    op.drop_column('orders', 'final_price')
    op.drop_column('orders', 'notes')
    op.drop_column('orders', 'created_at')
    # ### end Alembic commands ###
